### ISSUE TITLE
Add mailer service to simplify config

### ISSUE THREAD

**Issue by spwoodcock** [developmentseed/osm-seed#342]
### Issue

- Currently we rely on external SMTP providers, such as gmail.
- This adds an extra step to the setup.

### Solution

- Bundle a simple SMTP service that can be used to send email.
- Example (added as `mail.yml` compose file, to make it optional):

```yaml
version: '3'
services:
  mail:
    image: "ixdotai/smtp:v0.5.2"
    volumes:
      - ./rsa.private:/etc/exim4/dkim.key.temp:ro
    environment:
      - MAILNAME=osmseed.org
      - DKIM_KEY_PATH=/etc/exim4/dkim.key.temp
    restart: unless-stopped
```

> We can simply add an empty file `rsa.private` file somewhere in the repo to make this work (required by ixdotai/smtp).
